# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:
- job: "Test"
  strategy:
    matrix:
      LinuxPython27:
        python.version: "2.7"
        imageName: "ubuntu-16.04"
      LinuxPython35:
        python.version: "3.5"
        imageName: "ubuntu-16.04"
      LinuxPython36:
        python.version: "3.6"
        imageName: "ubuntu-16.04"
      LinuxPython37:
        python.version: "3.7"
        imageName: "ubuntu-16.04"
      MacPython27:
        python.version: "2.7"
        imageName: "macos-10.13"
      MacPython35:
        python.version: "3.5"
        imageName: "macos-10.13"
      MacPython36:
        python.version: "3.6"
        imageName: "macos-10.13"
      MacPython37:
        python.version: "3.7"
        imageName: "macos-10.13"
      WindowsPython27:
        python.version: "2.7"
        imageName: "vs2017-win2016"
      WindowsPython35:
        python.version: "3.5"
        imageName: "vs2017-win2016"
      WindowsPython36:

        python.version: "3.6"
        imageName: "vs2017-win2016"
      WindowsPython37:
        python.version: "3.7"
        imageName: "vs2017-win2016"
    maxParallel: 10
  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "$(python.version)"
      architecture: "x64"

  - script: python -m pip install --upgrade pip && pip install -r test_requirements.txt
    displayName: "Install dependencies"

  - script: |
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=mymodule --cov-report=xml --cov-report=html
    displayName: "pytest"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/test-results.xml"
      testRunTitle: $(Agent.JobName)
    condition: succeededOrFailed()

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

- job: "Publish"
  dependsOn: "Test"
  pool:
    vmImage: "Ubuntu-16.04"

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      architecture: "x64"

  - script: python setup.py sdist
    displayName: "Build sdist"
